version: "3"

services:
  db:
    image: "mysql"
    container_name: "mysql"
    environment:
      - MYSQL_DATABASE=war_resources
      - MYSQL_USER=warlord
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
        - backend
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
        test: mysql war_resources --user=warlord --password='pass' --silent --execute "SELECT 1;"
        interval: 30s
        timeout: 10s
        retries: 5 

  backend:
    build: "./WarResourcesAPI"
    container_name: "backend"
    ports:
      - "8080:8080"
    networks:
        - backend
        - frontend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/war_resources
      - SPRING_DATASOURCE_USERNAME=warlord
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
        db:
            condition: service_healthy

  frontend:
    build: "./war_resources_frontend"
    container_name: "frontend"
    ports:
      - "3000:3000"
    networks:
        - frontend
    depends_on:
      - backend
      
networks:
    frontend:
    backend: